[profile.dev]
split-debuginfo = "unpacked"

[workspace]
members = [
  "governance/addin-mock/program",
  "governance/addin-api",
  "governance/program",
  "governance/test-sdk",
  "governance/tools",
  "governance/chat/program",
]

exclude = [
]

resolver = "2"
